inherit_from: ./configs/Static/ScanNet/scannet.yaml
scene: scene0106_00

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/scene0106_00/processed/data
cam:
  H: 480 
  W: 640 
  fx: 579.395630
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609