inherit_from: ./configs/Static/ScanNet/scannet.yaml
scene: scene0169_00

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/scene0169_00/processed/data
cam:
  H: 480 
  W: 640 
  fx: 576.336243
  fy: 577.583801
  cx: 322.522797
  cy: 238.558853